### PR TITLE
Integrate flow.js

### PR DESCRIPTION
**Pull request by iranreyes**
by @DonghyukJacobJang

### CODE REVIEW

**Comment by ragu-S** [comment]
@iranreyes might want to close this in favour of typescript since it has better documentation and support for React now

**Comment by DonghyukJacobJang** [comment]
In my opinion and experience of using flow, I think it is too early to say that flow is great. I would rather using typescript instead.

**Comment by neo** [comment]
Based on the convo in #98, I think we picked flow b/c that's what the fb stack uses.

**Comment by neo** [comment]
But everyone knows I like TypeScript more, just a little bit more tho, not dramatically.

**Pull request closed without merging**
